; ============================================================================
; Bank $10 - Game Boy Color Colorization Engine
; ============================================================================
; Centralized per-screen colorization:
;   - Screen color descriptors: 8 BG + 8 OBJ palettes + compact tile->palette
;     LUT specs (data generated by tools/gen_color_data.py from
;     tools/screen_colors.json into screen_colors_data.inc).
;   - Bank10_OnMapLoad (via GBC_MapHook patched into RenderTilemapCell):
;     installs the descriptor assigned to the RLE map ID being loaded, so
;     attributes/palettes always match the screen being drawn.
;   - Bank10_Frame (via GBC_FrameHook in the main loop): recomputes the staged
;     CGB palettes from the descriptor's base colors through the DMG palette
;     shadows (reproducing fades/flashes/load-blackouts), and assigns OBJ
;     palette bits in shadow OAM from wOBJPalLUT.
;   - The VBlank trampoline (bank00) uploads staged palettes to CRAM and
;     detects DMG shadow changes.
;
; All routines here run with bank $10 mapped; callers bridge from ROM0.

SECTION "ROM Bank $010", ROMX[$4000], BANK[$10]


; ----------------------------------------------------------------------------
; Bank10_BootInit - called once at boot via GBC_BootBridge (LCD off).
; Installs descriptor 0 and blacks out CRAM: the game sets the DMG shadows to
; $FF (blackout) right after, and the first fade-in reveals the colors.
; ----------------------------------------------------------------------------
Bank10_BootInit::
    xor a
    call InstallDescriptor

    ; All-black CRAM while LCD is off
    ld a, $80
    ldh [rBCPS], a
    ld b, 64
    xor a
.bg:
    ldh [rBCPD], a
    dec b
    jr nz, .bg
    ld a, $80
    ldh [rOCPS], a
    ld b, 64
    xor a
.obj:
    ldh [rOCPD], a
    dec b
    jr nz, .obj

    ; Staging black too; shadows considered "seen" at $FF (blackout)
    ld hl, wPalStagingBG
    ld b, 128
    xor a
.stg:
    ld [hl+], a
    dec b
    jr nz, .stg
    ld a, $ff
    ld [wLastBGP], a
    ld [wLastOBP0], a
    ld [wLastOBP1], a
    xor a
    ld [wPalDirty], a
    ld [wFadeReq], a
    ld [wFading], a
    ld [wSnapReq], a
    ld [wFadePhase], a
    ld [wFadeMoved], a
    ret


; ----------------------------------------------------------------------------
; Bank10_OnMapLoad - in: E = RLE map ID (registers saved by GBC_MapHook).
; Installs the descriptor assigned to this map, if any and not already active.
; ----------------------------------------------------------------------------
Bank10_OnMapLoad::
    ld h, HIGH(MapColorTable)
    ld l, e
    ld a, [hl]
    cp $ff
    ret z                       ; no descriptor for this map -> keep current
    ld hl, wCurDescId
    cp [hl]
    ret z                       ; already active
    ; fall through into InstallDescriptor


; ----------------------------------------------------------------------------
; InstallDescriptor - in: A = descriptor id.
; Sets wCurDescId/Ptr, expands the BG and OBJ LUT specs into WRAM, and
; requests a palette recompute (rides the fade path: under a $FF blackout the
; new colors only appear with the fade-in, like the original DMG sequencing).
; ----------------------------------------------------------------------------
InstallDescriptor::
    ld [wCurDescId], a
    ld l, a                     ; HL = DescTable + id*8
    ld h, $00
    add hl, hl
    add hl, hl
    add hl, hl
    ld de, DescTable
    add hl, de
    ld a, l
    ld [wCurDescPtr], a
    ld a, h
    ld [wCurDescPtr+1], a
    inc hl                      ; skip BG/OBJ palette pointers
    inc hl
    inc hl
    inc hl
    ld a, [hl+]
    ld e, a
    ld a, [hl+]
    ld d, a                     ; DE = BG LUT spec
    push hl
    ld h, d
    ld l, e
    ld b, HIGH(wBGAttrLUT)
    call ExpandLutSpec
    pop hl
    ld a, [hl+]
    ld e, a
    ld a, [hl]
    ld d, a                     ; DE = OBJ LUT spec ($0000 = keep current)
    or e
    jr z, .no_obj
    ld h, d
    ld l, e
    ld b, HIGH(wOBJPalLUT)
    call ExpandLutSpec
.no_obj:
    ld a, $01
    ld [wFadeReq], a
    ld [wSnapReq], a            ; new screen's palettes swap in instantly
    ret


; ----------------------------------------------------------------------------
; ExpandLutSpec - in: HL = spec (db default, db n, n * [first, last, attr]),
;                     B = HIGH() of the 256-byte page-aligned dest LUT.
; ----------------------------------------------------------------------------
ExpandLutSpec:
    ld a, [hl+]                 ; default attribute
    ld d, b
    ld e, $00
.fill:
    ld [de], a
    inc e
    jr nz, .fill
    ld a, [hl+]                 ; record count
    or a
    ret z
    ld c, a
.rec:
    ld a, [hl+]                 ; first tile
    ld e, a
    ld a, [hl+]                 ; last tile (inclusive, >= first)
    sub e
    inc a
    push bc
    ld b, a                     ; B = run length
    ld a, [hl+]                 ; attribute
.set:
    ld [de], a
    inc e
    dec b
    jr nz, .set
    pop bc
    dec c
    jr nz, .rec
    ret


; ----------------------------------------------------------------------------
; Bank10_Frame - runs every main-loop iteration right after the shadow OAM
; rebuild (bridged by GBC_FrameHook).
; ----------------------------------------------------------------------------
Bank10_Frame::
    ; 1) On a DMG shadow change / screen switch, decide: instant snap (screen
    ;    loads, flash effects) or smooth per-frame fade (sequencer values).
    ld a, [wFadeReq]
    or a
    jp z, .step
    xor a
    ld [wFadeReq], a

    ld a, [wSnapReq]
    or a
    jr nz, .snap                ; screen switch: new base palettes, no lerp
    ld a, [BGP_SHADOW]
    ld hl, wLastBGP
    cp [hl]
    jr z, .snap                 ; OBP-only change = sprite flash effect
    or a
    jr z, .smooth               ; $00 \
    cp $40                      ;      |
    jr z, .smooth               ; $40  | the DMG fade sequencer only ever
    cp $90                      ;      | writes these BGP values; anything
    jr z, .smooth               ; $90  | else is a flash -> keep it instant
    cp $e4                      ;      |
    jr z, .smooth               ; $e4  |
    inc a                       ;      |
    jr nz, .snap                ; $ff /

.smooth:
    ld a, $01
    ld [wFading], a
    ld [wFadeMoved], a          ; force at least one full stepping cycle
    ; mirror the shadows ourselves (the snap path's remap normally does it)
    ; so the VBlank trampoline detects the next sequencer step
    ld a, [BGP_SHADOW]
    ld [wLastBGP], a
    ld a, [OBP0_SHADOW]
    ld [wLastOBP0], a
    ld a, [OBP1_SHADOW]
    ld [wLastOBP1], a
    jr .step

.snap:
    xor a
    ld [wSnapReq], a
    ld [wFading], a
    ld [wFadeMoved], a
    ld a, [wCurDescPtr]
    ld l, a
    ld a, [wCurDescPtr+1]
    ld h, a                     ; HL = descriptor
    ld a, [hl+]
    ld e, a
    ld a, [hl+]
    ld d, a                     ; DE = BG base palettes
    push hl
    ld a, [BGP_SHADOW]
    ld [wLastBGP], a
    ld c, a
    ld hl, wPalStagingBG
    ld b, 8
    call RemapPalettes
    pop hl
    ld a, [hl+]
    ld e, a
    ld a, [hl]
    ld d, a                     ; DE = OBJ base palettes
    ld a, [OBP0_SHADOW]
    ld [wLastOBP0], a
    ld c, a
    ld hl, wPalStagingOBJ
    ld b, 4                     ; OBJ palettes 0-3 follow OBP0
    call RemapPalettes
    ld a, [OBP1_SHADOW]
    ld [wLastOBP1], a
    ld c, a
    ld b, 4                     ; OBJ palettes 4-7 follow OBP1
    call RemapPalettes
    ld a, $01
    ld [wPalDirty], a
    jp .oam

.step:
    ; 2) Smooth fade: step one quarter of the palettes (16 colors) toward
    ;    their live targets each frame. Quartering keeps the worst-case cost
    ;    around ~3.4k M-cycles; each color still updates at 15Hz with a
    ;    FADE_STEP-unit move, which reads as a continuous ramp.
    ld a, [wFading]
    or a
    jr z, .oam
    xor a
    ld [wFadeScratch+2], a      ; moved-this-phase flag
    ld a, [wCurDescPtr]
    ld l, a
    ld a, [wCurDescPtr+1]
    ld h, a                     ; HL = descriptor
    ld a, [wFadePhase]
    ld c, a                     ; C = this frame's phase
    inc a
    and $03
    ld [wFadePhase], a
    ld a, c
    cp 2
    jr nc, .step_obj
    ; phases 0/1: BG palettes 0-3 / 4-7 under BGP
    ld a, [hl+]
    ld e, a
    ld a, [hl]
    ld d, a                     ; DE = BG base palettes
    ld hl, wPalStagingBG
    ld a, c
    or a
    jr z, .step_go_bg
    ld a, 32
    add a, e
    ld e, a
    jr nc, .step_bg_nc
    inc d
.step_bg_nc:
    ld hl, wPalStagingBG + 32
.step_go_bg:
    ld a, [BGP_SHADOW]
    jr .step_go
.step_obj:
    ; phases 2/3: OBJ palettes 0-3 under OBP0 / 4-7 under OBP1
    inc hl
    inc hl
    ld a, [hl+]
    ld e, a
    ld a, [hl]
    ld d, a                     ; DE = OBJ base palettes
    ld hl, wPalStagingOBJ
    ld a, c
    cp 2
    jr z, .step_go_obp0
    ld a, 32
    add a, e
    ld e, a
    jr nc, .step_obj_nc
    inc d
.step_obj_nc:
    ld hl, wPalStagingOBJ + 32
    ld a, [OBP1_SHADOW]
    jr .step_go
.step_go_obp0:
    ld a, [OBP0_SHADOW]
.step_go:
    ld c, a
    ld b, 4
    call StepPalettes
    ld a, [wFadeScratch+2]
    or a
    jr z, .step_quiet
    ld [wPalDirty], a           ; A = 1: upload this frame's movement
    ld [wFadeMoved], a
.step_quiet:
    ld a, [wFadePhase]          ; wrapped to 0 = a full cycle just finished
    or a
    jr nz, .oam
    ld a, [wFadeMoved]
    or a
    jr nz, .step_rearm
    ld [wFading], a             ; four quiet phases -> converged, stop
.step_rearm:
    xor a
    ld [wFadeMoved], a

.oam:
    ; 2) Assign CGB OBJ palette bits in shadow OAM from wOBJPalLUT.
    ;    DMG OBP1-class sprites (flags bit 4) map to palettes 4-7.
    ld hl, SHADOW_OAM
    ld c, 40
.entry:
    inc hl
    inc hl                      ; skip Y, X
    ld a, [hl+]                 ; tile id
    push hl
    ld h, HIGH(wOBJPalLUT)
    ld l, a
    ld b, [hl]                  ; palette 0-3
    pop hl
    ld a, [hl]                  ; flags
    bit 4, a
    jr z, .obp0_class
    set 2, b                    ; OBP1-class -> palettes 4-7
.obp0_class:
    and $F0                     ; keep priority/flips/bit4, clear bank+palette
    or b
    ld [hl+], a
    dec c
    jr nz, .entry
    ret


; ----------------------------------------------------------------------------
; RemapPalettes - in: DE = base palettes (8 bytes each), HL = staging dest,
;                     B = palette count, C = DMG mapping byte.
; CGB color slot i of each palette receives base color ((C >> 2i) & 3) --
; exactly the DMG BGP/OBP semantics, so fades behave like the original.
; Advances DE and HL by B*8. Preserves C.
; ----------------------------------------------------------------------------
RemapPalettes:
.pal:
    push bc
    ld a, c                     ; mapping byte
    ld b, 4
.slot:
    push af
    and $03
    add a, a                    ; color index * 2 bytes
    push de
    add a, e
    ld e, a
    jr nc, .no_carry
    inc d
.no_carry:
    ld a, [de]
    ld [hl+], a
    inc de
    ld a, [de]
    ld [hl+], a
    pop de
    pop af
    rrca
    rrca                        ; next 2 mapping bits
    dec b
    jr nz, .slot
    ld a, e                     ; next base palette
    add 8
    ld e, a
    jr nc, .no_carry2
    inc d
.no_carry2:
    pop bc
    dec b
    jr nz, .pal
    ret


; ----------------------------------------------------------------------------
; StepPalettes - smooth-fade variant of RemapPalettes. Instead of copying the
; DMG-mapped target colors, moves each staged RGB555 channel toward its target
; by at most FADE_STEP per call, so successive sequencer steps blend into one
; continuous 60fps ramp. Targets are recomputed on the fly from the base
; palettes + live shadow byte, so a step arriving mid-ramp just redirects the
; ramp (chained fades and reversals come out smooth for free).
; in: DE = base palettes, HL = staging, B = palette count, C = DMG mapping
; byte. Advances DE/HL by B*8. Sets wFadeScratch+2 if any channel moved.
; ----------------------------------------------------------------------------
DEF FADE_STEP EQU 4

StepPalettes:
.pal:
    push bc
    ld a, c                     ; mapping byte
    ld b, 4
.slot:
    push af
    push de
    and $03
    add a, a                    ; base color index * 2 bytes
    add a, e
    ld e, a
    jr nc, .nc1
    inc d
.nc1:
    ld a, [de]
    ld [wFadeScratch], a        ; target lo
    inc de
    ld a, [de]
    ld [wFadeScratch+1], a      ; target hi
    push bc
    ; red: bits 0-4 of lo
    ld a, [wFadeScratch]
    and $1f
    ld b, a
    ld a, [hl]
    and $1f
    ld c, a
    call StepChannel
    ld d, a                     ; D = new red
    ; green: (hi & 3) << 3 | lo >> 5
    ld a, [wFadeScratch+1]
    and $03
    rlca
    rlca
    rlca
    ld b, a
    ld a, [wFadeScratch]
    rlca
    rlca
    rlca
    and $07
    or b
    ld b, a                     ; B = target green
    inc hl
    ld a, [hl-]                 ; staged hi (HL back on lo)
    and $03
    rlca
    rlca
    rlca
    ld c, a
    ld a, [hl]
    rlca
    rlca
    rlca
    and $07
    or c
    ld c, a                     ; C = staged green
    call StepChannel
    ld e, a                     ; E = new green
    ; blue: bits 2-6 of hi
    ld a, [wFadeScratch+1]
    rrca
    rrca
    and $1f
    ld b, a
    inc hl
    ld a, [hl-]
    rrca
    rrca
    and $1f
    ld c, a
    call StepChannel
    ; repack: lo = red | green<<5, hi = green>>3 | blue<<2
    ld b, a                     ; B = new blue
    ld a, e
    rrca
    rrca
    rrca                        ; g2g1g0 000 g4g3
    ld c, a
    and $e0
    or d
    ld [hl+], a                 ; store lo
    ld a, c
    and $03
    ld c, a
    ld a, b
    add a, a
    add a, a
    or c
    ld [hl+], a                 ; store hi
    pop bc
    pop de
    pop af
    rrca
    rrca                        ; next 2 mapping bits
    dec b
    jr nz, .slot
    ld a, e                     ; next base palette
    add 8
    ld e, a
    jr nc, .nc2
    inc d
.nc2:
    pop bc
    dec b
    jp nz, .pal
    ret


; ----------------------------------------------------------------------------
; StepChannel - move staged channel C toward target B by at most FADE_STEP,
; clamping at the target. out: A = new value. Marks wFadeScratch+2 on motion.
; ----------------------------------------------------------------------------
StepChannel:
    ld a, c
    cp b
    ret z
    jr c, .up
    sub FADE_STEP               ; staged above target: darken
    jr c, .floor
    cp b
    jr nc, .moved
.floor:
    ld a, b
    jr .moved
.up:
    add FADE_STEP               ; staged below target: brighten
    cp b
    jr c, .moved
    ld a, b
.moved:
    push af
    ld a, $01
    ld [wFadeScratch+2], a
    pop af
    ret


; ----------------------------------------------------------------------------
; Bank10_ApplyChrPatches - called via GBC_ChrPatchRet right after a CHR
; dispatch entry finished loading (bank10 mapped, wChrEntry = entry id).
; Overwrites edited tiles in VRAM with patch data from ChrPatchTable
; (generated by tools/gen_tile_patches.py from the studio's pixel edits).
; HBlank-safe: 2 bytes per mode-0 wait (LCD off -> no waiting).
; ----------------------------------------------------------------------------
Bank10_ApplyChrPatches::
    ld a, [wChrEntry]
    add a, a
    ld e, a
    ld d, $00
    ld hl, ChrPatchTable
    add hl, de
    ld a, [hl+]
    ld h, [hl]
    ld l, a                     ; HL = patch list ($0000 = none)
    or h
    ret z
    ld a, [hl+]                 ; patch count
    or a
    ret z
    ld b, a
.patch:
    ld a, [hl+]
    ld e, a
    ld a, [hl+]
    ld d, a                     ; DE = VRAM dest of this tile
    ld c, 8                     ; 8 bursts x 2 bytes = 16 bytes
.burst:
.wait:
    ldh a, [rSTAT]
    and $03
    jr nz, .wait
    ld a, [hl+]
    ld [de], a
    inc de
    ld a, [hl+]
    ld [de], a
    inc de
    dec c
    jr nz, .burst
    dec b
    jr nz, .patch
    ret


; ----------------------------------------------------------------------------
; Generated color data: DescTable, palettes, LUT specs, MapColorTable
; ----------------------------------------------------------------------------
INCLUDE "extensions/screen_colors_data.inc"

; Generated tile pixel patches: ChrPatchTable (per CHR dispatch entry)
INCLUDE "extensions/tile_patches.inc"

    ds $8000 - @, 0
