"""Generate src/graphics/bank11_sprite_gfx.asm from tools/gfx/sprites/*.png.

The game's animation interpreter (ROM0 Call_000_1f2a / Call_000_1fa0) streams
raw sprite graphics from a bank-local table (`dw ptr` * N at $4000, each entry
`db tile_count, tile_count * 16 bytes 2bpp`). Originally that table lives in
frozen bank $0A; the GBC build points the two loaders at bank $11 instead,
whose content is generated here from the editable PNGs (byte-identical to
bank $0A as long as the PNGs are untouched).

Sources:
  tools/gfx/sprites/index.json   tile count + layout per sprite (export_gfx.py)
  tools/gfx/sprites/spr_NNN.png  the pixels (edit these). A missing PNG (or an
                                 entry with 0 tiles) falls back to bank $0A.
"""

import json
import os

from PIL import Image

from chr_codec import encode_2bpp, load_rom
from export_gfx import GFX, image_levels, levels_tile, read_sprites

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
OUT_PATH = os.path.join(ROOT, "src", "graphics", "bank11_sprite_gfx.asm")
SPRITES = os.path.join(GFX, "sprites")
BANK = 0x11


def sprite_tiles_from_png(path, layout):
    levels = image_levels(Image.open(path))
    return [bytes(encode_2bpp(levels_tile(levels, x, y))) for x, y in layout]


def main():
    rom = load_rom()
    original = read_sprites(rom)
    index = {}
    if os.path.isfile(os.path.join(SPRITES, "index.json")):
        with open(os.path.join(SPRITES, "index.json")) as f:
            index = {int(k): v for k, v in json.load(f).items()}

    entries = []
    edited = 0
    for i, orig in enumerate(original):
        tiles = orig
        info = index.get(i)
        path = os.path.join(SPRITES, f"spr_{i:03d}.png")
        if info and info["tiles"] and os.path.isfile(path):
            tiles = sprite_tiles_from_png(path, info["layout"])
            assert len(tiles) == info["tiles"]
            assert len(tiles) <= 255
            if tiles != orig:
                edited += 1
        entries.append(tiles)

    lines = [
        "; AUTO-GENERATED by tools/gen_sprite_gfx.py from tools/gfx/sprites/*.png",
        "; DO NOT EDIT - regenerate with: python tools/gen_sprite_gfx.py",
        ";",
        "; Relocated copy of the bank $0A sprite graphics table used by the",
        "; animation interpreter (ROM0 Call_000_1f2a / Call_000_1fa0 map this",
        "; bank instead of $0A). Format: `dw ptr` per sprite, then per sprite",
        "; `db tile_count` + tile_count * 16 bytes 2bpp.",
        "",
        f'SECTION "ROM Bank ${BANK:03x}", ROMX[$4000], BANK[${BANK:x}]',
        "",
        "SpriteGfxTable:",
    ]
    for i in range(0, len(entries), 8):
        lines.append("    dw " + ", ".join(f"SpriteGfx_{k:03d}"
                                           for k in range(i, min(i + 8, len(entries)))))
    lines.append("")
    for i, tiles in enumerate(entries):
        lines.append(f"SpriteGfx_{i:03d}:")
        lines.append(f"    db {len(tiles)}")
        for t in tiles:
            lines.append("    db " + ", ".join(f"${b:02X}" for b in t))
    lines.append("")
    lines.append("    ASSERT @ <= $8000")
    lines.append("")
    with open(OUT_PATH, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_PATH}: {len(entries)} sprites, {edited} edited vs bank $0A")


if __name__ == "__main__":
    main()
