"""Generate src/extensions/tile_patches.inc from tools/tile_edits.json.

tile_edits.json schema (written by the studio UI):
{
  "patches": {
    "<chr_entry_id>": {            // dispatch entry 0-22, as decimal string
      "<tile_index>": [64 ints]    // 0-3 gray levels, row-major 8x8,
    }                              // index relative to the entry's dispatch VRAM dest
  },
  "remaps": {                      // per-cell tile-id remaps (screen view
    "<map_id>": {                  // "Replace with..."), RLE map id as
      "<row>,<col>": tile_id      // decimal string; row 0-17, col 0-19
    }
  }
}

Emits ChrPatchTable (23 pointers) + per-entry patch lists:
  db count, then count * [dest_lo, dest_hi, 16 bytes 2bpp].
VRAM dest = CHR_TABLE[entry].dest + tile_index*16 (tile_index checked against
the entry's decoded length, see chr_codec.py).
Also emits MapRemapTable, applied to the $d000 tilemap shadow right after a
map is decompressed: db map_id, count, count * [row, col, tile_id], ...,
terminated by db $FF.
"""

import json
import os

from chr_codec import CHR_TABLE, NUM_ENTRIES, encode_2bpp, load_rom, lz_decode

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
EDITS_PATH = os.path.join(TOOLS, "tile_edits.json")
DATA_PATH = os.path.join(TOOLS, "kit", "data.json")
OUT_PATH = os.path.join(ROOT, "src", "extensions", "tile_patches.inc")
# Any ROM with the original graphics banks works for measuring entry lengths.
ROM_PATHS = [os.path.join(ROOT, "bin", "game.gb"),
             os.path.join(ROOT, "bin", "Tetris Plus (USA, Europe) (SGB Enhanced).gb")]


def entry_geometry():
    """(dest, length) per entry: dispatch-table VRAM dest + decoded length,
    from the built ROM when available (tools/chr_codec.py), else from the kit
    export (which records the same values). Tile indices in tile_edits.json
    are relative to this dest."""
    for path in ROM_PATHS:
        if os.path.isfile(path):
            rom = load_rom(path)
            return {e: (dest, len(lz_decode(rom, bank, src)))
                    for e, (bank, src, dest) in CHR_TABLE.items()}
    if not os.path.isfile(DATA_PATH):
        return {}
    with open(DATA_PATH) as f:
        data = json.load(f)
    return {int(k): (v["dest"], v["length"])
            for k, v in data.get("chr_entries", {}).items()}


def main():
    edits = {"patches": {}}
    if os.path.isfile(EDITS_PATH):
        with open(EDITS_PATH) as f:
            edits = json.load(f)

    geo = entry_geometry()
    lines = [
        "; AUTO-GENERATED by tools/gen_tile_patches.py from tools/tile_edits.json",
        "; DO NOT EDIT - regenerate with: python tools/gen_tile_patches.py",
        "",
    ]
    pointers = []
    bodies = []
    total = 0
    for entry in range(NUM_ENTRIES):
        patches = edits.get("patches", {}).get(str(entry), {})
        if not patches:
            pointers.append("$0000")
            continue
        assert len(patches) <= 255,             f"entry {entry}: {len(patches)} patched tiles, max 255 (1-byte count)"
        label = f"ChrPatches_{entry:02d}"
        pointers.append(label)
        body = [f"{label}:", f"    db {len(patches)}"]
        for tile_index_s in sorted(patches, key=int):
            tile_index = int(tile_index_s)
            if entry in geo:
                base, length = geo[entry]
                assert tile_index * 16 < length, \
                    f"entry {entry} tile {tile_index}: beyond loaded data " \
                    f"({length} bytes)"
            else:
                base = CHR_TABLE[entry][2]
            dest = base + tile_index * 16
            assert 0x8000 <= dest <= 0x97F0, \
                f"entry {entry} tile {tile_index}: dest {dest:#06x} outside VRAM"
            data = encode_2bpp(patches[tile_index_s])
            body.append(f"    db ${dest & 0xFF:02X}, ${dest >> 8:02X}  "
                        f"; tile {tile_index} @ ${dest:04X}")
            for off in (0, 8):
                body.append("    db " + ", ".join(f"${b:02X}"
                                                  for b in data[off:off + 8]))
            total += 1
        bodies.append("\n".join(body))

    lines.append("ChrPatchTable:")
    for i in range(0, NUM_ENTRIES, 4):
        lines.append("    dw " + ", ".join(pointers[i:i + 4]))
    lines.append("")
    lines.extend(bodies)
    lines.append("")

    remap_count = 0
    lines.append("MapRemapTable:")
    for map_id_s in sorted(edits.get("remaps", {}), key=int):
        cells = edits["remaps"][map_id_s]
        if not cells:
            continue
        map_id = int(map_id_s)
        assert 0 <= map_id <= 0xFE, f"remap map id {map_id} out of range"
        assert len(cells) <= 255, f"remap map {map_id}: too many cells"
        lines.append(f"    db ${map_id:02X}, {len(cells)}  "
                     f"; map ${map_id:02X}: {len(cells)} cell(s)")
        for cell_s in sorted(cells, key=lambda s: [int(v) for v in s.split(",")]):
            row, col = (int(v) for v in cell_s.split(","))
            tile = int(cells[cell_s])
            assert 0 <= row < 18 and 0 <= col < 20, \
                f"remap map {map_id} cell {cell_s}: outside 20x18 screen"
            assert 0 <= tile <= 0xFF, \
                f"remap map {map_id} cell {cell_s}: bad tile id {tile}"
            lines.append(f"    db {row}, {col}, ${tile:02X}")
            remap_count += 1
        lines.append("")
    lines.append("    db $FF  ; end of MapRemapTable")
    lines.append("")

    with open(OUT_PATH, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_PATH}: {total} tile patches, {remap_count} cell remaps")


if __name__ == "__main__":
    main()
