"""Generate src/extensions/screen_colors_data.inc from tools/screen_colors.json.

JSON schema:
{
  "descriptors": {
    "<name>": {
      "bg_palettes":  [["#RRGGBB" x4] x up-to-8],   // padded with last entry
      "obj_palettes": [["#RRGGBB" x4] x up-to-8],
      "bg_lut":  {"default": attr, "ranges": [[first, last, attr], ...]},
      "obj_lut": {"default": pal,  "ranges": [...]} | null   // null = keep
    }, ...
  },
  "descriptor_order": ["<name>", ...],          // index 0 is the boot default
  "map_assignments": {"0xNN": "<name>", ...}    // RLE map id -> descriptor
}

Palette slot convention: index 0..3 = DMG color 0..3 (light -> dark); the
engine remaps slots through the BGP/OBP shadows at runtime, so palettes here
are the "fully visible" base colors.
"""

import json
import os
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
JSON_PATH = os.path.join(TOOLS, "screen_colors.json")
OUT_PATH = os.path.join(ROOT, "src", "extensions", "screen_colors_data.inc")


def rgb555(color):
    if isinstance(color, str):
        c = color.lstrip("#")
        r, g, b = int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16)
    else:
        r, g, b = color
    return (b >> 3) << 10 | (g >> 3) << 5 | (r >> 3)


def emit_palettes(lines, label, pals):
    pals = list(pals)
    if not pals:
        pals = [["#FFFFFF", "#A5A5A5", "#525252", "#000000"]]
    while len(pals) < 8:
        pals.append(pals[-1])
    lines.append(f"{label}:")
    for p in pals[:8]:
        assert len(p) == 4, f"{label}: palette needs 4 colors, got {p}"
        words = ", ".join(f"${rgb555(c):04X}" for c in p)
        lines.append(f"    dw {words}")


def emit_spec(lines, label, lut):
    # Order preserved: like the runtime expander, later ranges override
    # earlier ones on overlap ("last wins").
    ranges = lut.get("ranges", [])
    lines.append(f"{label}:")
    lines.append(f"    db ${lut.get('default', 0):02X}  ; default attribute")
    lines.append(f"    db {len(ranges)}    ; range count")
    for first, last, attr in ranges:
        assert 0 <= first <= last <= 255 and 0 <= attr <= 255, (label, first, last, attr)
        lines.append(f"    db ${first:02X}, ${last:02X}, ${attr:02X}")


def main():
    with open(JSON_PATH) as f:
        cfg = json.load(f)

    order = cfg["descriptor_order"]
    descs = cfg["descriptors"]
    assert len(order) <= 32, "too many descriptors"
    for name in order:
        assert name in descs, f"descriptor_order references unknown '{name}'"

    lines = [
        "; AUTO-GENERATED by tools/gen_color_data.py from tools/screen_colors.json",
        "; DO NOT EDIT - regenerate with: python tools/gen_color_data.py",
        "",
        "DescTable:",
    ]
    for name in order:
        d = descs[name]
        obj_spec = "$0000" if d.get("obj_lut") is None else f"Spec_{name}_obj"
        lines.append(f"    dw Pal_{name}_bg, Pal_{name}_obj, "
                     f"Spec_{name}_bg, {obj_spec}  ; id {order.index(name)}")
    lines.append("")

    for name in order:
        d = descs[name]
        emit_palettes(lines, f"Pal_{name}_bg", d.get("bg_palettes", []))
        emit_palettes(lines, f"Pal_{name}_obj", d.get("obj_palettes", []))
        emit_spec(lines, f"Spec_{name}_bg", d.get("bg_lut", {}))
        if d.get("obj_lut") is not None:
            emit_spec(lines, f"Spec_{name}_obj", d["obj_lut"])
        lines.append("")

    table = [0xFF] * 256
    for key, name in cfg.get("map_assignments", {}).items():
        map_id = int(key, 0)
        table[map_id] = order.index(name)
    lines.append("    ds ($100 - (@ % $100)) % $100  ; align to 256-byte page")
    lines.append("MapColorTable:")
    for row in range(0, 256, 16):
        vals = ", ".join(f"${v:02X}" for v in table[row:row + 16])
        lines.append(f"    db {vals}")
    lines.append("")

    with open(OUT_PATH, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_PATH}: {len(order)} descriptors, "
          f"{sum(1 for v in table if v != 0xFF)} maps assigned")


if __name__ == "__main__":
    main()
